version: "3.9"

services:
    app:
        build: ./
        entrypoint: python main.py
        depends_on: [db]
    db:
        image: postgres:13.0-alpine
        restart: always
        environment:
            - DB_DBNAME=NQueens
            - DB_USER=nqueens
            - DB_PASS=nqueens
            - DB_PORT=5432
            - DB_HOST=127.0.0.1
