version: "3"

services:
  app:
    build: ./
    entrypoint: python main.py
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:13.1
    container_name: postgres_container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
       - "./sql:/docker-entrypoint-initdb.d"
    ports:
      - 5433:5432
